Techstorm: Techstorm Namespace Reference
Techstorm Namespace Reference
Namespaces
namespace Application
namespace BroadPhaseLayers
namespace DevTools
namespace Layers
Classes
class abstract
This is an abstract interface singleton that all projects must implement and set the ProjectReference singleton to their project. If this boilerplate code is not done, Techstorm will not know what to run. In terms of functionality, this interface just holds the functions and variables that Techstorm will call (besides some initialization). Do not directly call window code in here or your project will crash!
class BPLayerInterface
struct CameraData
class ConfigFileRegistry
struct EngineConfig
class FileSystemRegistry
class GameCamera
class GameObject
A game object that can be rendered to the screen. Inherits from IGameObject, and already provides the basic rendering functionality. If you override this class, you should inherit the function.
class GameObjectRegistry
Game object registry, it stores all game objects in the world and manages their updating, rendering, destruction, creation, etc.
class GamePhysics
class Gate
A class that acts as, well, a gate! It is essentially as a piece of machinery on an assembly line. Please do note, that this is a template class and is not meant to be used directly. Please see GameObjectRegistry for more information and an example.
class GlobalsContainer
class InputDispatcher
class LayerRegistry
class MyBodyActivationListener
class ObjectContactListener
class ObjectLPF
class ObjectVsBroadPhaseLF
class PlaneObject
class Renderer
Serves as the renderer for the game.
class Singleton
A singleton class, it does what singletons do. The template (T) must be the type that is inheriting from this class, otherwise there will be issues.
class TechstormEngine
struct Vec2
struct Vec3
struct Vec4
class Window
struct WindowDecorations
Window decorations are a set of parameters that are used to configure the window. This includes title, width, height, window config, and target FPS.
class World
Typedefs
using FilePathMeta = { const std::string cPath
using DirectoryFiles = std::vector< std::string >
using FileSystemMeta = { std::string extension
using GameSettings = GameSettings { const int cMaxThreads=-1
Serves as the settings for the game. Please note that cMaxThreads must be at least 2. If you want Techstorm to decide, set cMaxThreads to -1.
using InputEvents = eventpp::EventDispatcher< int, void()>
using ObjectLayer = JPH::ObjectLayer
using Depth = int
Enumerations
enum class EReturnCode : int {
SUCCESSFUL_OPERATION , SUCCESSFUL_OPERATION_WITH_WARNING , SUCCESSFUL_OPERATION_WITH_CAUGHT_EXCEPTION , ERROR_UNKNOWN = -1 ,
ERROR_INVALID_ARGS = -2 , ERROR_INVALID_VALUE = -3
}
Functions
bool FileSystemIsProperlyFormatted (const char *rootPath, const char *directoryMapPath)
int InitializeScripting ()
Initializes the scripting API.
int RegisterLua (sol::state &lua)
Registers the scripting API for Lua.
int RegisterAngelScript ()
Registers the scripting API for AngelScript.
template<typename T >
T & GetGlobal (const std::string &key)
template<typename T >
void SetGlobal (const std::string &key, const T &value)
Variables
const std::string cDirectoryName
std::string path
std::string filename
Typedef Documentation
Depth
using Techstorm::Depth = typedef int
Definition at line 7 of file RenderLayer.h.
DirectoryFiles
using Techstorm::DirectoryFiles = typedef std::vector<std::string>
Definition at line 10 of file FileSystem.h.
FilePathMeta
using Techstorm::FilePathMeta = typedef { const std::string cPath
Definition at line 5 of file FilePathMeta.h.
FileSystemMeta
using Techstorm::FileSystemMeta = typedef { std::string extension
Definition at line 12 of file FileSystem.h.
GameSettings
using Techstorm::GameSettings = typedef GameSettings { const int cMaxThreads = -1
Serves as the settings for the game. Please note that cMaxThreads must be at least 2. If you want Techstorm to decide, set cMaxThreads to -1.
Definition at line 9 of file GameSettings.h.
InputEvents
using Techstorm::InputEvents = typedef eventpp::EventDispatcher<int, void()>
Definition at line 5 of file Input.h.
ObjectLayer
using Techstorm::ObjectLayer = typedef JPH::ObjectLayer
Definition at line 58 of file Physics.h.
Enumeration Type Documentation
EReturnCode
enum class Techstorm::EReturnCode : int strong
Enumerator
SUCCESSFUL_OPERATION
SUCCESSFUL_OPERATION_WITH_WARNING
SUCCESSFUL_OPERATION_WITH_CAUGHT_EXCEPTION
ERROR_UNKNOWN
ERROR_INVALID_ARGS
ERROR_INVALID_VALUE
Definition at line 4 of file EReturnCode.h.
Function Documentation
FileSystemIsProperlyFormatted()
bool Techstorm::FileSystemIsProperlyFormatted (const char * rootPath, const char * directoryMapPath)
Definition at line 3 of file FileSystem.cpp.
GetGlobal()
template<typename T > T & Techstorm::GetGlobal (const std::string & key)
Definition at line 31 of file Globals.h.
References Techstorm::GlobalsContainer::get(), and Techstorm::Singleton< GlobalsContainer >::Instance().
InitializeScripting()
int Techstorm::InitializeScripting ()
Initializes the scripting API.
Initializes the scripting.
Returns
an integer value that represents the result of the operation.
Returns
Definition at line 7 of file ScriptingAPI.cpp.
RegisterAngelScript()
int Techstorm::RegisterAngelScript ()
Registers the scripting API for AngelScript.
Returns
an integer value that represents the result of the operation.
Definition at line 17 of file ScriptingAPI.cpp.
RegisterLua()
int Techstorm::RegisterLua (sol::state & lua)
Registers the scripting API for Lua.
Parameters
lua The lua state to register the API to.
Returns
an integer value that represents the result of the operation.
Definition at line 12 of file ScriptingAPI.cpp.
SetGlobal()
template<typename T > void Techstorm::SetGlobal (const std::string & key, const T & value)
Definition at line 38 of file Globals.h.
References Techstorm::Singleton< GlobalsContainer >::Instance(), and Techstorm::GlobalsContainer::set().
Variable Documentation
cDirectoryName
const std::string Techstorm::cDirectoryName
Definition at line 7 of file FilePathMeta.h.
filename
std::string Techstorm::filename
Definition at line 15 of file FileSystem.h.
Referenced by Techstorm::FileSystemRegistry::FileSystemRegistry().
path
std::string Techstorm::path
Definition at line 14 of file FileSystem.h.
Referenced by Techstorm::FileSystemRegistry::FileSystemRegistry().